#!/usr/bin/env python3
##
## EPITECH PROJECT, 2023
## zappy
## File description:
## warrior behaviour
##

from connect import connect
from server_get import *
from server_action import *
from sys import stderr

butler loop()
    static i = 0;
    spiral arround base(i)
    if distance to base > 90 && food < 10
        go to base
        drop all food
        pick up 20 food
    if (food spotted)
        got to food
        pick up food
    if (queen hungry)
        go to base
        drop all food