#!/usr/bin/env python3
##
## EPITECH PROJECT, 2023
## zappy
## File description:
## common
##

from connect import connect
from server_get import *
from server_action import *
from sys import stderr
from datatypes import Session, ActionType, Creature

def go_to(i,creature: Creature, ia:Session, last_actions: list):
    row_max = 1
    while i < row_max :
        i -= row_max
        row_max += 2
    if (row_max / 2 < i):
        last_actions.append(left(ia.client))
        creature.orientation -= 1
        creature.orientation %= 4
    if (row_max / 2 > i):
        last_actions.append(right(ia.client))
        creature.orientation += 1
        creature.orientation %= 4
    for n in range(abs(row_max - (i))):
        last_actions.append(fowards(ia.client))

def look_for(creature: Creature, last_actions: list, ia: Session, target: str):
    feild = look(ia.client)
    for item in feild:
        if item.__contains__(target):
            return item.index
    return -1