#!/usr/bin/env python3
##
## EPITECH PROJECT, 2023
## zappy
## File description:
## warrior behaviour
##

from connect import connect
from server_get import *
from server_action import *
from sys import stderr

def spiral(i):
    while i > 0:
        i -= 1
        fowards()
        if look() != -1:
            return True
    right()
    return False

def warrior_loop():
    static time_to_ritual = -1
    if time_to_ritual == 0:
        start ritual
    if time_to_ritual >= 0
        time_to_ritual -= 1;
    answer messages(received messages)
    if (food > 20):
        fowards()
        if (enemy spotted):
            say(enemy spotted)
            go_to(enemy_position)
        if (receive message of enemy position && distance < 20)
            move_to(enemy_position.x, enmey position.y)
    else:
        butler_loop()
